name: Doc Site Build
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build:
    name: Build Doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Find variables
        id: vars
        # if on master branch push, use "dev", otherwise major.minor
        run: |
          [ "$GITHUB_REF_NAME" = "master" ] && (echo version=dev >> $GITHUB_OUTPUT) || (echo version=$GITHUB_REF_NAME | cut -d "." -f 1,2 >> $GITHUB_OUTPUT)
          echo git_msg=\"$(git log -1 --pretty=format:'%s')\" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install npm packages
        run: npm ci
      - name: Build the document
        run: npm run doc -- --gitRevision $GITHUB_REF_NAME
      - name: Checkout the site
        uses: actions/checkout@v4
        with:
          path: site
          ref: gh-pages
      - name: build site
        run: |
          rm -rf site/${{ steps.vars.outputs.version }}
          mv _site site/${{ steps.vars.outputs.version }}
      - name: Commit to site branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: site
          branch: gh-pages
          commit_message: Doc of version ${{ steps.vars.outputs.version }} generated from ${{ steps.vars.outputs.sha_short }} ${{ steps.vars.outputs.git_msg }}
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
